version: "3.9"

services:
  axonserver:
    image: axoniq/axonserver:2023.2.2-jdk-17
    container_name: axon-avro-axonserver
    ports:
      - "8024:8024"
      - "8124:8124"
    volumes:
      - .docker/axonserver/config:/axonserver/config:ro
      - .docker/axonserver/data:/axonserver/data
      - .docker/axonserver/events:/axonserver/events
      - .docker/axonserver/plugins:/axonserver/plugins
