<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.holixon.axon.avro._</groupId>
    <artifactId>axon-avro-root</artifactId>
    <version>0.0.1-SNAPSHOT</version>
  </parent>

  <groupId>io.holixon.axon.avro</groupId>
  <artifactId>axon-avro-bom</artifactId>
  <description>Bill of material for axon-avro.</description>
  <packaging>pom</packaging>

  <dependencyManagement>
    <dependencies>
      <!-- AVRO-KOTLIN -->
      <dependency>
        <groupId>io.toolisticon.kotlin.avro</groupId>
        <artifactId>avro-kotlin-bom</artifactId>
        <version>${avro-kotlin.version}</version>
        <scope>import</scope>
        <type>pom</type>
      </dependency>

      <dependency>
        <groupId>io.holixon.axon.avro</groupId>
        <artifactId>axon-avro-generation</artifactId>
        <version>${project.version}</version>
      </dependency>

      <dependency>
        <groupId>io.holixon.axon.avro</groupId>
        <artifactId>axon-avro-kotlin-serializer</artifactId>
        <version>${project.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
</project>
