services:
  axonserver:
    image: axoniq/axonserver:2023.2.6-jdk-17
    container_name: axon-avro-holi-bank-example
    ports:
      - "8024:8024"
      - "8124:8124"
    environment:
      AXONIQ_AXONSERVER_DEVMODE_ENABLED: true
      AXONIQ_AXONSERVER_STANDALONE: true

