logging:
  level:
    org.springframework.core.annotation.AnnotationTypeMapping: ERROR
    org.axonframework.eventhandling.tokenstore.inmemory.InMemoryTokenStore: ERROR

axon:
  metrics:
    auto-configuration:
      enabled: false
#spring:
#  autoconfigure:
#    exclude: org.axonframework.springboot.autoconfig.AxonTracingAutoConfiguration
