axoniq:
  axonserver:
    name: axon-avro-local
    hostname: localhost
    standalone: true
    accesscontrol:
      enabled: false
      token-dir: ./data
      admin-token: 934f816e-027e-4f3d-a34c-679a2354d562
      token: 934f816e-027e-4f3d-a34c-679a2354d562
    devmode:
      enabled: true
